### ISSUE TITLE
Calendar function

### ISSUE THREAD

**Issue by mhulton** [sttir/WeightLoss#1]
I'd like to add old data, but your calendar doesn't go back beyond 2017. Can this be fixed? I have data as far back as 2008. Thanks.

**Comment by nixnoughtnothing** [comment]
@mhulton Hi, we’ll fix this in a future update and sorry for the inconvenience.Your feedback is much appreciated!

**Comment by nixnoughtnothing** [comment]
Resolved on the latest version(1.2.2)
